trainer:
  num_epochs: 300
  warmup: 2
  train_ratio: 0.8
  lr: 0.001
  min_lr: 0.0000001
  optimizer: adamw
  weight_decay: 0.05
  weight_decay_end: 0.04
  pred_ratio_var: 0
  resume: False

dataset:
  data_root: /workspace/Encvis/Code/CVC-ClinicDB
  batch_size: 8
  num_workers: 4
  image_size: 352
  train_ratio: 0.8

finetune:
  checkpoint: CVC_Slim

slim_unetr:
  in_channels: 3 
  out_channels: 1 
  embed_dim: 96
  embedding_dim: 121
  channels: [24, 48, 60]
  blocks: [1, 2, 3, 2]
  heads: [1, 2, 4, 4]
  r: [4, 2, 2, 1]
  distillation: False
  dropout: 0.3





